name: Java CI
on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Actions for Apache Maven
      uses: actions/checkout@v1
    - run: |
        mvn clean install
        mvn test
        mvn site

    - name: Upload target Directory
      uses: actions/upload-artifact@v2
      with:
        name: target-directory
        path: target/

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "target/**/TEST-*.xml"
      if: always()

  codequality:
    runs-on: ubuntu-latest
    steps:
    - name: code scan
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: pmd/pmd-github-action@v2
      with:
        rulesets: 'ruleset.xml'

