name: Java CI
on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Actions for Apache Maven
      uses: actions/checkout@v1
    - run: |
        mvn clean install
        mvn test
        mvn site

    - name: Upload target Directory
      uses: actions/upload-artifact@v2
      with:
        name: target-directory
        path: target/

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "target/**/TEST-*.xml"
      if: always()

    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: JEST Tests                  # Name of the check run which will be created
        path: "target/**/TEST-*.xml"      # Path to test results (inside artifact .zip)
        reporter: jest-junit 
