name: Java CI
on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Actions for Apache Maven
      uses: actions/checkout@v1
    - run: |
        mvn clean install
        mvn test
        mvn site

    - name: Upload target Directory
      uses: actions/upload-artifact@v2
      with:
        name: target-directory
        path: target/

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "target/**/TEST-*.xml"
      if: always()

    - name: HTML Preview
      id: html_preview
      uses: pavi2410/html-preview-action@v2
      with:
        html_file: 'target/site/index.html'

    - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
